// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// build_tree_network_cpp
List build_tree_network_cpp(CharacterVector var_conc, IntegerVector var_tip_id, IntegerVector nodeSZ, NumericVector dpthST, LogicalVector is_leaf);
RcppExport SEXP _multiRF_build_tree_network_cpp(SEXP var_concSEXP, SEXP var_tip_idSEXP, SEXP nodeSZSEXP, SEXP dpthSTSEXP, SEXP is_leafSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type var_conc(var_concSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type var_tip_id(var_tip_idSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type nodeSZ(nodeSZSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type dpthST(dpthSTSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type is_leaf(is_leafSEXP);
    rcpp_result_gen = Rcpp::wrap(build_tree_network_cpp(var_conc, var_tip_id, nodeSZ, dpthST, is_leaf));
    return rcpp_result_gen;
END_RCPP
}
// compute_split_stats_cpp
NumericVector compute_split_stats_cpp(NumericMatrix Y, IntegerVector membership, int mem_left, int mem_right);
RcppExport SEXP _multiRF_compute_split_stats_cpp(SEXP YSEXP, SEXP membershipSEXP, SEXP mem_leftSEXP, SEXP mem_rightSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type Y(YSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type membership(membershipSEXP);
    Rcpp::traits::input_parameter< int >::type mem_left(mem_leftSEXP);
    Rcpp::traits::input_parameter< int >::type mem_right(mem_rightSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_split_stats_cpp(Y, membership, mem_left, mem_right));
    return rcpp_result_gen;
END_RCPP
}
// fit_mv_forest_cpp
List fit_mv_forest_cpp(NumericMatrix X, NumericMatrix Y, int ntree, int mtry, int ytry, int nodesize_min, int max_depth, int seed, int nthread);
RcppExport SEXP _multiRF_fit_mv_forest_cpp(SEXP XSEXP, SEXP YSEXP, SEXP ntreeSEXP, SEXP mtrySEXP, SEXP ytrySEXP, SEXP nodesize_minSEXP, SEXP max_depthSEXP, SEXP seedSEXP, SEXP nthreadSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Y(YSEXP);
    Rcpp::traits::input_parameter< int >::type ntree(ntreeSEXP);
    Rcpp::traits::input_parameter< int >::type mtry(mtrySEXP);
    Rcpp::traits::input_parameter< int >::type ytry(ytrySEXP);
    Rcpp::traits::input_parameter< int >::type nodesize_min(nodesize_minSEXP);
    Rcpp::traits::input_parameter< int >::type max_depth(max_depthSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< int >::type nthread(nthreadSEXP);
    rcpp_result_gen = Rcpp::wrap(fit_mv_forest_cpp(X, Y, ntree, mtry, ytry, nodesize_min, max_depth, seed, nthread));
    return rcpp_result_gen;
END_RCPP
}
// fit_mv_forest_unsup_cpp
List fit_mv_forest_unsup_cpp(NumericMatrix data, int ntree, int ytry, int nodesize_min, int max_depth, int seed, int nthread);
RcppExport SEXP _multiRF_fit_mv_forest_unsup_cpp(SEXP dataSEXP, SEXP ntreeSEXP, SEXP ytrySEXP, SEXP nodesize_minSEXP, SEXP max_depthSEXP, SEXP seedSEXP, SEXP nthreadSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type data(dataSEXP);
    Rcpp::traits::input_parameter< int >::type ntree(ntreeSEXP);
    Rcpp::traits::input_parameter< int >::type ytry(ytrySEXP);
    Rcpp::traits::input_parameter< int >::type nodesize_min(nodesize_minSEXP);
    Rcpp::traits::input_parameter< int >::type max_depth(max_depthSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< int >::type nthread(nthreadSEXP);
    rcpp_result_gen = Rcpp::wrap(fit_mv_forest_unsup_cpp(data, ntree, ytry, nodesize_min, max_depth, seed, nthread));
    return rcpp_result_gen;
END_RCPP
}
// tsne_cost_gradient_cpp
NumericMatrix tsne_cost_gradient_cpp(NumericMatrix Y, NumericMatrix P);
RcppExport SEXP _multiRF_tsne_cost_gradient_cpp(SEXP YSEXP, SEXP PSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type Y(YSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type P(PSEXP);
    rcpp_result_gen = Rcpp::wrap(tsne_cost_gradient_cpp(Y, P));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_multiRF_build_tree_network_cpp", (DL_FUNC) &_multiRF_build_tree_network_cpp, 5},
    {"_multiRF_compute_split_stats_cpp", (DL_FUNC) &_multiRF_compute_split_stats_cpp, 4},
    {"_multiRF_fit_mv_forest_cpp", (DL_FUNC) &_multiRF_fit_mv_forest_cpp, 9},
    {"_multiRF_fit_mv_forest_unsup_cpp", (DL_FUNC) &_multiRF_fit_mv_forest_unsup_cpp, 7},
    {"_multiRF_tsne_cost_gradient_cpp", (DL_FUNC) &_multiRF_tsne_cost_gradient_cpp, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_multiRF(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
