# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

build_tree_network_cpp <- function(var_conc, var_tip_id, nodeSZ, dpthST, is_leaf) {
    .Call(`_multiRF_build_tree_network_cpp`, var_conc, var_tip_id, nodeSZ, dpthST, is_leaf)
}

compute_split_stats_cpp <- function(Y, membership, mem_left, mem_right) {
    .Call(`_multiRF_compute_split_stats_cpp`, Y, membership, mem_left, mem_right)
}

fit_mv_forest_cpp <- function(X, Y, ntree = 500L, mtry = 0L, ytry = 0L, nsplit = 10L, nodesize_min = 5L, max_depth = 0L, seed = -1L, nthread = 0L, samptype = 0L, prox_mode = 0L, embed = NULL, sibling_gamma = 0.5, enhanced_prox_mode = 0L) {
    .Call(`_multiRF_fit_mv_forest_cpp`, X, Y, ntree, mtry, ytry, nsplit, nodesize_min, max_depth, seed, nthread, samptype, prox_mode, embed, sibling_gamma, enhanced_prox_mode)
}

fit_mv_forest_unsup_cpp <- function(data, ntree = 500L, ytry = 10L, nodesize_min = 5L, max_depth = 0L, seed = -1L, nthread = 0L, samptype = 0L, prox_mode = 0L, embed = NULL, sibling_gamma = 0.5, enhanced_prox_mode = 0L) {
    .Call(`_multiRF_fit_mv_forest_unsup_cpp`, data, ntree, ytry, nodesize_min, max_depth, seed, nthread, samptype, prox_mode, embed, sibling_gamma, enhanced_prox_mode)
}

tsne_cost_gradient_cpp <- function(Y, P) {
    .Call(`_multiRF_tsne_cost_gradient_cpp`, Y, P)
}

